import type { Metadata } from "next";
import { IBM_Plex_Sans_KR, Cookie } from "next/font/google";
import "./globals.css";

const ibmPlexSansKR = IBM_Plex_Sans_KR({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--font-ibm-plex",
});

const cookie = Cookie({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cookie",
});

export const metadata: Metadata = {
  title: "Mini Studio-Dress-Makeup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSansKR.variable} ${cookie.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
